[package]
name = "sayo_pbr_rs"
version = "0.1.0"
authors = ["Sabyasachi Mukherjee <sabyasachimukherjee2006@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
toml = "*"
byteorder = "1" #for writing pfm file
tobj = "*"
log = "0.4"
flexi_logger = "^0.11.4"
crossbeam = "0.7"
num_cpus = "*"
minifb = "*"

[profile.release]
#debug = true